package com.alpha0.app.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.platform.LocalConfiguration
import java.util.Locale

@Immutable
class AppStrings internal constructor(
    val language: AppLanguage,
    private val values: Map<String, String>,
) {
    fun text(key: String, vararg args: Any?): String {
        val pattern = values[key] ?: ENGLISH[key] ?: key
        return if (args.isEmpty()) pattern else String.format(locale(), pattern, *args)
    }

    private fun locale(): Locale = if (language == AppLanguage.RUSSIAN) Locale.forLanguageTag("ru") else Locale.ENGLISH
}

val LocalAppStrings = staticCompositionLocalOf { AppStrings(AppLanguage.ENGLISH, ENGLISH) }

@Composable
fun rememberAppStrings(selected: AppLanguage): AppStrings {
    val systemLanguage = LocalConfiguration.current.locales.get(0)?.language
    val resolved = when (selected) {
        AppLanguage.SYSTEM -> if (systemLanguage == "ru") AppLanguage.RUSSIAN else AppLanguage.ENGLISH
        else -> selected
    }
    return AppStrings(resolved, if (resolved == AppLanguage.RUSSIAN) RUSSIAN else ENGLISH)
}

internal val ENGLISH = mapOf(
    "app_name" to "SENTINEL",
    "status_verified" to "Verified",
    "status_active" to "Active",
    "status_pending" to "Pending",
    "status_warning" to "Warning",
    "status_denied" to "Denied",
    "status_revoked_label" to "Revoked",
    "status_failed" to "Failed",
    "status_unknown" to "Unknown",
    "status_unavailable" to "Unavailable",
    "status_stopped" to "Stopped",
    "security_posture" to "Security posture",
    "security_posture_subtitle" to "Account authority and trusted device state, separated by scope.",
    "account" to "Account",
    "signed_in" to "Signed in",
    "verified_session" to "Verified session",
    "trusted_device" to "Trusted device",
    "attention" to "Attention",
    "attention_required" to "Action required",
    "no_required_action" to "No required action",
    "loaded_states_current" to "All loaded authority states are current.",
    "review_security_state" to "Review the security state before continuing.",
    "state_unavailable" to "State unavailable",
    "open_device_identity" to "Open device identity",
    "recent_activity" to "Recent activity",
    "recent_activity_limited" to "Open Activity for the server-backed account and security history.",
    "sessions_scope_body" to "This screen represents the current authenticated device session. Account and security history is available in Activity.",
    "support" to "Support",
    "limited_view" to "Limited view",
    "activity_limited_title" to "Activity evidence is intentionally limited",
    "activity_limited_body" to "This screen does not fabricate an audit timeline. It shows only locally available bounded state until server-backed activity events are exposed.",
    "security_subtitle" to "Account authority and trusted identity are separated by scope.",
    "mfa_full" to "Multi-factor authentication",
    "recovery" to "Recovery",
    "sessions" to "Sessions",
    "device_identity" to "Device identity",
    "linked_providers_title" to "Linked providers",
    "recovery_codes_available" to "Recovery codes available",
    "sessions_current_only" to "Current authenticated device session",
    "device_identity_subtitle" to "This device · server-authoritative state",
    "linked_providers_subtitle" to "Verified external identities linked to this account",
    "dangerous_actions_scope" to "Dangerous actions live inside their scoped detail screens.",
    "menu" to "Menu",
    "settings" to "Settings",
    "updates" to "Updates",
    "help" to "Help",
    "about" to "About",
    "export_logs" to "Export logs",
    "physical_banner" to "PHYSICAL TEST · STAGING · %s · %s",
    "home" to "Home",
    "games" to "Games",
    "security" to "Security",
    "activity" to "Activity",
    "sign_in_title" to "Sign in to your account",
    "create_account_title" to "Create your account",
    "mfa_title" to "Verify your second factor",
    "mfa_explanation" to "Enter the current authenticator code or one unused recovery code. No SENTINEL session exists until this check succeeds.",
    "mfa_required" to "Your first sign-in factor is valid. Second-factor verification is required.",
    "mfa_code" to "Authenticator code",
    "mfa_code_required" to "Enter a current authenticator or recovery code.",
    "mfa_invalid" to "The authenticator or recovery code is invalid, expired, replayed, or already used.",
    "mfa_expired" to "The MFA sign-in challenge expired. Start sign-in again.",
    "verify_mfa" to "Verify and sign in",
    "auth_explanation" to "Your account is separate from this device identity. Device enrollment follows after authentication.",
    "email" to "Email",
    "password" to "Password",
    "valid_email" to "Enter a valid email address.",
    "password_length" to "Password must be at least 12 characters.",
    "email_exists" to "An account with this email already exists.",
    "show_password" to "Show password",
    "hide_password" to "Hide password",
    "sign_in" to "Sign in",
    "create_account" to "Create account",
    "new_account" to "Create a new account",
    "existing_account" to "I already have an account",
    "invalid_credentials" to "Check the email and password.",
    "server_unreachable" to "Cannot reach the SENTINEL server.",
    "request_timeout" to "The staging server is still waking up. Wait a moment and try again.",
    "register_unknown" to "The account may already have been created. Wait for staging, then choose Sign in instead of registering again.",
    "auth_failed" to "Authentication failed: %s",
    "forgot_password" to "Forgot password?",
    "reset_password_title" to "Reset your password",
    "reset_password_explanation" to "Enter your email to request a one-time reset code. The response never reveals whether an account exists.",
    "send_reset_code" to "Send reset code",
    "reset_sent" to "If the account exists, a reset code has been sent.",
    "auth_code" to "One-time code",
    "auth_code_required" to "Enter the complete one-time code.",
    "auth_code_invalid" to "The one-time code is invalid, expired, or already used.",
    "new_password" to "New password",
    "reset_password" to "Reset password",
    "password_reset_complete" to "Password updated. Sign in with the new password.",
    "back_to_sign_in" to "Back to sign in",
    "verify_email_title" to "Verify your email",
    "verify_email_explanation" to "Enter the one-time code sent to your email. Verification can be completed later without blocking device setup.",
    "verification_sent" to "Verification requested. Check your inbox for the one-time code.",
    "verify_email" to "Verify email",
    "send_verification_code" to "Send verification code",
    "email_verified" to "Email verified.",
    "resend_code" to "Send a new code",
    "account_verify_email_hint" to "Send a one-time verification code to this account email, then enter it below.",
    "verification_code_required" to "Enter the verification code.",
    "verify_later" to "Verify later",
    "working" to "Working…",
    "or_continue_with" to "Or continue securely with",
    "continue_google" to "Continue with Google",
    "continue_telegram" to "Continue with Telegram",
    "continue_vk" to "Continue with VK",
    "federated_opening" to "Opening %s sign-in…",
    "federated_completing" to "Completing secure sign-in…",
    "federated_return_hint" to "Complete sign-in in %s, then return to SENTINEL.",
    "federated_cancelled" to "Sign-in was cancelled.",
    "federated_expired" to "The sign-in request expired. Start it again.",
    "federated_failed" to "Secure provider sign-in failed: %s",
    "provider_not_configured" to "This sign-in provider is not configured yet.",
    "account_link_required" to "This email already belongs to a SENTINEL account. Sign in with your existing account first; SENTINEL will never auto-link accounts by matching email.",
    "browser_unavailable" to "No secure browser is available for this sign-in flow.",
    "federated_privacy" to "SENTINEL trusts the provider's verified account identifier, never an email match alone. Provider passwords and access tokens are not stored in the app.",
    "account_security" to "Account access",
    "account_email" to "Email: %s",
    "mfa_status" to "Two-factor authentication: %s",
    "mfa_recovery_remaining" to "Unused recovery codes: %s",
    "enable_mfa" to "Enable authenticator MFA",
    "disable_mfa" to "Disable authenticator MFA",
    "confirm_mfa" to "Confirm authenticator",
    "open_authenticator" to "Open authenticator app",
    "authenticator_unavailable" to "No authenticator app accepted the secure setup link. Add the secret manually instead.",
    "mfa_setup_instructions" to "Open your TOTP authenticator with the button below, or add the secret manually, then enter the current 6-digit code. The secret is shown only during this enrollment.",
    "mfa_secret" to "Authenticator secret: %s",
    "mfa_or_recovery_code" to "Authenticator or recovery code",
    "rotate_recovery_codes" to "Replace recovery codes",
    "mfa_enrollment_started" to "Authenticator enrollment started. Confirm it with a current code.",
    "mfa_enabled_relogin" to "MFA enabled. Existing sessions were revoked; save the recovery codes, then sign in again.",
    "mfa_disabled" to "MFA disabled. Existing sessions were revoked.",
    "mfa_recovery_rotated" to "Recovery codes replaced. Previous unused codes are no longer valid.",
    "mfa_recovery_title" to "Recovery codes",
    "mfa_recovery_warning" to "Store these codes offline. Each code works once and SENTINEL will not display this set again.",
    "continue_sign_in" to "I saved the codes — sign in again",
    "email_verified_status" to "EMAIL VERIFIED",
    "email_unverified_status" to "EMAIL NOT VERIFIED",
    "password_status" to "Password sign-in: %s",
    "enabled" to "Enabled",
    "disabled" to "Disabled",
    "linked_providers" to "Linked providers: %s",
    "none" to "None",
    "link_provider" to "Add another secure sign-in method",
    "link_google" to "Link Google",
    "link_telegram" to "Link Telegram",
    "link_vk" to "Link VK",
    "provider_linked" to "Provider linked to this SENTINEL account.",
    "provider_link_conflict" to "That provider identity is already linked to another account or this provider is already linked.",
    "provider_link_return_hint" to "Complete linking in %s, then return to SENTINEL.",
    "provider_link_privacy" to "Linking requires your current SENTINEL session and a fresh provider proof. Matching email addresses never link accounts automatically.",
    "provider_ready_to_link" to "Ready to link",
    "provider_not_enabled_here" to "Not enabled in this environment",
    "provider_environment_unavailable" to "No external sign-in provider is enabled for this environment. Linking becomes available after provider registration and environment configuration.",
    "device_setup" to "Device setup",
    "device_setup_intro" to "Connect this phone in three clear steps. The private key never leaves Android Keystore.",
    "step_identity" to "1. Device identity",
    "step_background" to "2. Background operation",
    "step_proof" to "3. Secure connection",
    "identity_ready" to "Hardware-backed identity is ready",
    "background_explanation" to "Allowing background operation helps prevent delayed requests. You can change this later in Android settings.",
    "allow_background" to "Allow background operation",
    "background_allowed" to "Background operation is allowed",
    "bind_device" to "Connect and verify this phone",
    "retry_proof" to "Retry verification",
    "setup_busy" to "Connecting securely…",
    "setup_failed" to "Device setup failed: %s",
    "setup_privacy" to "Only the public key and its fingerprint are sent to SENTINEL.",
    "dashboard" to "Command center",
    "dashboard_subtitle" to "Your device, game access and SENTINEL services",
    "loading" to "Loading…",
    "loading_status" to "Loading SENTINEL status…",
    "load_failed" to "Could not load data: %s",
    "retry" to "Retry",
    "device" to "Device",
    "device_secure" to "Protected by Android Keystore",
    "device_details" to "Device security",
    "quality_feedback" to "Support and diagnostics",
    "report_problem" to "Report a problem",
    "report_problem_description" to "Describe a problem and attach a privacy-bounded diagnostic snapshot only with your consent.",
    "report_intro" to "Help improve SENTINEL with a reproducible report. Diagnostic data stays on this device until you submit this form.",
    "category" to "Category",
    "category_functionality" to "Functionality",
    "category_design" to "Design / visual",
    "category_game" to "Game integration",
    "category_performance" to "Performance",
    "category_accessibility" to "Accessibility",
    "category_voice" to "Voice / audio",
    "category_security" to "Security / privacy",
    "category_other" to "Other",
    "short_summary" to "Short summary",
    "no_secrets" to "Do not include passwords, tokens or private credentials.",
    "what_happened" to "What happened?",
    "what_happened_hint" to "Describe what you expected and what actually happened. This text is never copied into diagnostic logs.",
    "diagnostic_snapshot" to "Diagnostic snapshot",
    "diagnostic_stats" to "%s structured events · %s KiB · %s",
    "diagnostic_contents" to "Contains lifecycle, screen routes, safe actions, API timing, device/runtime state and sanitized errors. It excludes screenshots, raw audio, passwords/tokens, request bodies, game chat and SavedVariables.",
    "diagnostic_retention" to "If sent, diagnostic payloads are retained for up to 30 days; the ticket can remain for support history.",
    "attach_diagnostics" to "Attach this diagnostic snapshot to my report",
    "quality_program" to "Quality improvement program",
    "quality_program_body" to "Optional. Allow this report and attached sanitized diagnostics to improve reliability, design, accessibility and game integration.",
    "quality_program_opt_in" to "Contribute this report to SENTINEL quality improvement",
    "physical_forensics" to "Physical-test diagnostics",
    "physical_forensics_body" to "This isolated test build keeps a larger local trace. Export it only when deeper evidence is required.",
    "export_full_log" to "Export full diagnostic log",
    "report_submit_failed" to "Report could not be submitted: %s",
    "report_received" to "Report received",
    "reference" to "Reference: %s",
    "status" to "Status: %s",
    "problem_group" to "Problem group: %s",
    "initial_severity" to "Initial severity: %s",
    "related_reports" to "This problem group already contains %s related reports.",
    "diagnostics_attached" to "Diagnostics attached%s",
    "expires" to " · expires %s",
    "no_diagnostics_attached" to "No diagnostics were attached.",
    "sending" to "Sending…",
    "submit_report" to "Submit report",
    "cancel" to "Cancel",
    "game_access" to "Game access",
    "no_entitlements" to "No game access is assigned to this account yet.",
    "valid_until" to "Valid until: %s",
    "sign_out" to "Sign out",
    "signing_out" to "Signing out…",
    "game_details" to "Game details",
    "platform" to "Platform: %s",
    "family" to "Family: %s",
    "versioning" to "Versioning: %s",
    "launcher_supported" to "Launcher supported: %s",
    "interaction_mode" to "Interaction mode: %s",
    "state_security" to "State and security",
    "algorithm" to "Algorithm: %s",
    "bound" to "Connected: %s",
    "last_seen" to "Last seen: %s",
    "fingerprint" to "Fingerprint: %s",
    "source" to "Source: %s",
    "valid_from" to "Valid from: %s",
    "status_revoked" to "REVOKED",
    "status_at_risk" to "AT RISK",
    "rotate_key" to "Rotate device key",
    "revoke_device" to "Disconnect this device",
    "rotation_success" to "Device key was rotated successfully.",
    "revoked" to "This device was disconnected. Sign in again to continue.",
    "settings_title" to "Settings",
    "language" to "Language",
    "language_system" to "Use system language",
    "language_ru" to "Русский",
    "language_en" to "English",
    "appearance" to "Appearance",
    "theme_system" to "Use system theme",
    "theme_light" to "Light",
    "theme_dark" to "Dark",
    "settings_applied" to "Changes are applied immediately and saved on this device.",
    "updates_title" to "App updates",
    "current_version" to "Current version",
    "build_channel" to "Channel",
    "channel_development" to "Development",
    "channel_diagnostic" to "Diagnostic APK",
    "channel_play" to "Google Play",
    "source_revision" to "Source revision",
    "check_updates" to "Check for updates",
    "install_update" to "Install downloaded update",
    "checking_updates" to "Checking for updates…",
    "up_to_date" to "You are using the latest available version.",
    "update_available" to "A new version is available.",
    "update_downloading" to "Google Play is downloading the update…",
    "update_ready" to "The update is downloaded and ready to install.",
    "update_play_required" to "Secure automatic updates become available after this build is installed from the Google Play internal testing track.",
    "update_sideload_notice" to "This diagnostic APK was installed outside Google Play. Android may request confirmation or Play Protect verification for a replacement APK.",
    "open_play_store" to "Open Google Play",
    "help_title" to "Help",
    "help_getting_started" to "Getting started",
    "help_getting_started_body" to "Sign in, connect this phone, then use the command center to review device security and game access.",
    "help_security" to "Security and privacy",
    "help_security_body" to "Passwords, session tokens and private keys are never included in exported diagnostics. Device keys remain in Android Keystore.",
    "help_updates" to "Updates",
    "help_updates_body" to "Open Menu → Updates. Play-installed builds can update without uninstalling the app or losing local state.",
    "help_support" to "Support",
    "help_support_body" to "For a reproducible problem, use Report a problem or export test logs through the red diagnostic banner.",
    "about_title" to "About SENTINEL",
    "about_body" to "SENTINEL is a trustworthy player platform that connects device security, game access, diagnostics and intelligence.",
    "diagnostic_build" to "Diagnostic physical-test build",
    "games_title" to "Games and access",
    "games_description" to "Server-authoritative entitlements assigned to your account.",
    "activity_title" to "Activity",
    "activity_description" to "Server-backed account, security and connection history for this SENTINEL account.",
    "activity_empty_title" to "No recorded activity yet",
    "activity_empty_body" to "New account and security events will appear here as SENTINEL Core records them.",
    "activity_event_allowed" to "Recorded",
    "activity_event_denied" to "Denied",
    "activity_event_resource" to "Resource: %s",
    "activity_event_reason" to "Reason: %s",
    "activity_event_time" to "Time: %s",
    "activity_session" to "Account session is active",
    "activity_device" to "Device identity is connected",
    "activity_logs" to "Diagnostic events remain on this device until you explicitly export or attach them.",
    "not_available" to "Not available",
    "yes" to "Yes",
    "no" to "No",
    "back" to "Back",
)

internal val RUSSIAN = mapOf(
    "app_name" to "SENTINEL",
    "status_verified" to "Подтверждено",
    "status_active" to "Активно",
    "status_pending" to "Ожидание",
    "status_warning" to "Внимание",
    "status_denied" to "Запрещено",
    "status_revoked_label" to "Отозвано",
    "status_failed" to "Ошибка",
    "status_unknown" to "Неизвестно",
    "status_unavailable" to "Недоступно",
    "status_stopped" to "Остановлено",
    "security_posture" to "Состояние безопасности",
    "security_posture_subtitle" to "Состояния аккаунта и доверенного устройства разделены по области ответственности.",
    "account" to "Аккаунт",
    "signed_in" to "Вход выполнен",
    "verified_session" to "Сессия подтверждена",
    "trusted_device" to "Доверенное устройство",
    "attention" to "Внимание",
    "attention_required" to "Требуется действие",
    "no_required_action" to "Действий не требуется",
    "loaded_states_current" to "Все загруженные состояния актуальны.",
    "review_security_state" to "Проверьте состояние безопасности перед продолжением.",
    "state_unavailable" to "Состояние недоступно",
    "open_device_identity" to "Открыть идентификацию устройства",
    "recent_activity" to "Недавняя активность",
    "recent_activity_limited" to "Откройте «События» для серверной истории действий аккаунта и защиты.",
    "sessions_scope_body" to "Этот экран показывает текущую аутентифицированную сессию устройства. История аккаунта и защиты доступна в разделе «События».",
    "support" to "Поддержка",
    "limited_view" to "Ограниченный режим",
    "activity_limited_title" to "Данные активности намеренно ограничены",
    "activity_limited_body" to "Экран не имитирует полноценную ленту аудита. До появления серверных событий показываются только доступные ограниченные состояния.",
    "security_subtitle" to "Полномочия аккаунта и доверенная идентичность разделены по областям.",
    "mfa_full" to "Многофакторная аутентификация",
    "recovery" to "Восстановление",
    "sessions" to "Сессии",
    "device_identity" to "Идентификация устройства",
    "linked_providers_title" to "Связанные провайдеры",
    "recovery_codes_available" to "Коды восстановления доступны",
    "sessions_current_only" to "Текущая сессия этого устройства",
    "device_identity_subtitle" to "Это устройство · серверное состояние",
    "linked_providers_subtitle" to "Проверенные внешние идентификаторы, связанные с аккаунтом",
    "dangerous_actions_scope" to "Опасные действия находятся только внутри соответствующих детальных экранов.",
    "menu" to "Меню",
    "settings" to "Настройки",
    "updates" to "Обновление",
    "help" to "Справка",
    "about" to "О приложении",
    "export_logs" to "Экспорт логов",
    "physical_banner" to "ФИЗИЧЕСКИЙ ТЕСТ · STAGING · %s · %s",
    "home" to "Главная",
    "games" to "Игры",
    "security" to "Защита",
    "activity" to "События",
    "sign_in_title" to "Вход в аккаунт",
    "create_account_title" to "Создание аккаунта",
    "mfa_title" to "Подтверждение второго фактора",
    "mfa_explanation" to "Введите текущий код приложения-аутентификатора или один неиспользованный резервный код. Сессия SENTINEL не создаётся до успешной проверки.",
    "mfa_required" to "Первый фактор входа подтверждён. Требуется проверка второго фактора.",
    "mfa_code" to "Код аутентификатора",
    "mfa_code_required" to "Введите текущий код аутентификатора или резервный код.",
    "mfa_invalid" to "Код аутентификатора или резервный код неверен, истёк, повторно использован либо уже был погашен.",
    "mfa_expired" to "Запрос MFA истёк. Начните вход заново.",
    "verify_mfa" to "Подтвердить и войти",
    "auth_explanation" to "Аккаунт и идентификатор телефона разделены. Привязка устройства выполняется после входа.",
    "email" to "Электронная почта",
    "password" to "Пароль",
    "valid_email" to "Введите корректный адрес электронной почты.",
    "password_length" to "Пароль должен содержать не менее 12 символов.",
    "email_exists" to "Аккаунт с этим адресом уже существует.",
    "show_password" to "Показать пароль",
    "hide_password" to "Скрыть пароль",
    "sign_in" to "Войти",
    "create_account" to "Создать аккаунт",
    "new_account" to "Создать новый аккаунт",
    "existing_account" to "У меня уже есть аккаунт",
    "invalid_credentials" to "Проверьте адрес электронной почты и пароль.",
    "server_unreachable" to "Не удалось связаться с сервером SENTINEL.",
    "request_timeout" to "Тестовый сервер ещё запускается. Немного подождите и повторите попытку.",
    "register_unknown" to "Аккаунт мог быть создан. Дождитесь запуска сервера и выберите вход вместо повторной регистрации.",
    "auth_failed" to "Ошибка авторизации: %s",
    "forgot_password" to "Забыли пароль?",
    "reset_password_title" to "Восстановление пароля",
    "reset_password_explanation" to "Введите электронную почту, чтобы запросить одноразовый код. Ответ не раскрывает, существует ли такой аккаунт.",
    "send_reset_code" to "Отправить код восстановления",
    "reset_sent" to "Если аккаунт существует, код восстановления отправлен.",
    "auth_code" to "Одноразовый код",
    "auth_code_required" to "Введите полный одноразовый код.",
    "auth_code_invalid" to "Код недействителен, истёк или уже был использован.",
    "new_password" to "Новый пароль",
    "reset_password" to "Сменить пароль",
    "password_reset_complete" to "Пароль изменён. Войдите с новым паролем.",
    "back_to_sign_in" to "Вернуться ко входу",
    "verify_email_title" to "Подтверждение почты",
    "verify_email_explanation" to "Введите одноразовый код из письма. Подтверждение можно выполнить позже, оно не блокирует настройку устройства.",
    "verification_sent" to "Запрос подтверждения принят. Проверьте почту — туда должен прийти одноразовый код.",
    "verify_email" to "Подтвердить почту",
    "send_verification_code" to "Отправить код подтверждения",
    "email_verified" to "Почта подтверждена.",
    "resend_code" to "Отправить новый код",
    "account_verify_email_hint" to "Отправьте одноразовый код на почту этого аккаунта и введите его ниже.",
    "verification_code_required" to "Введите код подтверждения.",
    "verify_later" to "Подтвердить позже",
    "working" to "Выполняется…",
    "or_continue_with" to "Или безопасно продолжить через",
    "continue_google" to "Продолжить через Google",
    "continue_telegram" to "Продолжить через Telegram",
    "continue_vk" to "Продолжить через VK",
    "federated_opening" to "Открывается вход через %s…",
    "federated_completing" to "Завершается безопасный вход…",
    "federated_return_hint" to "Завершите вход в %s и вернитесь в SENTINEL.",
    "federated_cancelled" to "Вход отменён.",
    "federated_expired" to "Запрос на вход истёк. Запустите его заново.",
    "federated_failed" to "Ошибка безопасного входа через провайдера: %s",
    "provider_not_configured" to "Этот способ входа пока не настроен.",
    "account_link_required" to "Эта почта уже принадлежит аккаунту SENTINEL. Сначала войдите в существующий аккаунт — SENTINEL никогда не связывает аккаунты автоматически только по совпадению почты.",
    "browser_unavailable" to "Для этого способа входа не найден безопасный браузер.",
    "federated_privacy" to "SENTINEL доверяет проверенному идентификатору аккаунта провайдера, а не совпадению почты. Пароли и access-токены провайдера в приложении не сохраняются.",
    "account_security" to "Доступ к аккаунту",
    "account_email" to "Почта: %s",
    "mfa_status" to "Двухфакторная аутентификация: %s",
    "mfa_recovery_remaining" to "Неиспользованных резервных кодов: %s",
    "enable_mfa" to "Включить MFA через аутентификатор",
    "disable_mfa" to "Отключить MFA",
    "confirm_mfa" to "Подтвердить аутентификатор",
    "open_authenticator" to "Открыть приложение-аутентификатор",
    "authenticator_unavailable" to "Ни одно приложение-аутентификатор не приняло безопасную ссылку настройки. Добавьте секрет вручную.",
    "mfa_setup_instructions" to "Откройте TOTP-аутентификатор кнопкой ниже или добавьте секрет вручную, затем введите текущий 6-значный код. Секрет показывается только во время этой настройки.",
    "mfa_secret" to "Секрет аутентификатора: %s",
    "mfa_or_recovery_code" to "Код аутентификатора или резервный код",
    "rotate_recovery_codes" to "Заменить резервные коды",
    "mfa_enrollment_started" to "Настройка аутентификатора начата. Подтвердите её текущим кодом.",
    "mfa_enabled_relogin" to "MFA включена. Старые сессии отозваны; сохраните резервные коды и войдите снова.",
    "mfa_disabled" to "MFA отключена. Старые сессии отозваны.",
    "mfa_recovery_rotated" to "Резервные коды заменены. Старые неиспользованные коды больше недействительны.",
    "mfa_recovery_title" to "Резервные коды",
    "mfa_recovery_warning" to "Сохраните эти коды офлайн. Каждый код действует один раз, и этот набор больше не будет показан.",
    "continue_sign_in" to "Коды сохранены — войти снова",
    "email_verified_status" to "ПОЧТА ПОДТВЕРЖДЕНА",
    "email_unverified_status" to "ПОЧТА НЕ ПОДТВЕРЖДЕНА",
    "password_status" to "Вход по паролю: %s",
    "enabled" to "Включён",
    "disabled" to "Отключён",
    "linked_providers" to "Привязанные провайдеры: %s",
    "none" to "Нет",
    "link_provider" to "Добавить ещё один безопасный способ входа",
    "link_google" to "Привязать Google",
    "link_telegram" to "Привязать Telegram",
    "link_vk" to "Привязать VK",
    "provider_linked" to "Провайдер привязан к этому аккаунту SENTINEL.",
    "provider_link_conflict" to "Этот аккаунт провайдера уже привязан к другому аккаунту либо данный провайдер уже подключён.",
    "provider_link_return_hint" to "Завершите привязку в %s и вернитесь в SENTINEL.",
    "provider_link_privacy" to "Для привязки нужна текущая сессия SENTINEL и новое подтверждение у провайдера. Совпадение почты никогда не связывает аккаунты автоматически.",
    "provider_ready_to_link" to "Готов к привязке",
    "provider_not_enabled_here" to "Не включён в этой среде",
    "provider_environment_unavailable" to "В этой среде не включён ни один внешний провайдер. Привязка станет доступна после регистрации приложений провайдеров и настройки окружения.",
    "device_setup" to "Настройка устройства",
    "device_setup_intro" to "Подключите телефон за три понятных шага. Закрытый ключ никогда не покидает Android Keystore.",
    "step_identity" to "1. Идентификатор устройства",
    "step_background" to "2. Фоновая работа",
    "step_proof" to "3. Безопасное подключение",
    "identity_ready" to "Аппаратный идентификатор готов",
    "background_explanation" to "Фоновая работа помогает избежать задержек запросов. Разрешение можно изменить позднее в настройках Android.",
    "allow_background" to "Разрешить фоновую работу",
    "background_allowed" to "Фоновая работа разрешена",
    "bind_device" to "Подключить и подтвердить телефон",
    "retry_proof" to "Повторить подтверждение",
    "setup_busy" to "Выполняется безопасное подключение…",
    "setup_failed" to "Ошибка настройки устройства: %s",
    "setup_privacy" to "В SENTINEL отправляются только открытый ключ и его отпечаток.",
    "dashboard" to "Центр управления",
    "dashboard_subtitle" to "Ваше устройство, доступ к играм и сервисы SENTINEL",
    "loading" to "Загрузка…",
    "loading_status" to "Загрузка состояния SENTINEL…",
    "load_failed" to "Не удалось загрузить данные: %s",
    "retry" to "Повторить",
    "device" to "Устройство",
    "device_secure" to "Защищено Android Keystore",
    "device_details" to "Защита устройства",
    "quality_feedback" to "Поддержка и диагностика",
    "report_problem" to "Сообщить о проблеме",
    "report_problem_description" to "Опишите проблему и приложите ограниченную диагностику только с вашего согласия.",
    "report_intro" to "Помогите улучшить SENTINEL с помощью воспроизводимого отчёта. Диагностика остаётся на устройстве до отправки формы.",
    "category" to "Категория",
    "category_functionality" to "Функциональность",
    "category_design" to "Дизайн и отображение",
    "category_game" to "Интеграция с играми",
    "category_performance" to "Производительность",
    "category_accessibility" to "Специальные возможности",
    "category_voice" to "Голос и звук",
    "category_security" to "Безопасность и конфиденциальность",
    "category_other" to "Другое",
    "short_summary" to "Краткое описание",
    "no_secrets" to "Не указывайте пароли, токены и закрытые данные.",
    "what_happened" to "Что произошло?",
    "what_happened_hint" to "Опишите ожидаемое и фактическое поведение. Этот текст не копируется в диагностические логи.",
    "diagnostic_snapshot" to "Диагностический снимок",
    "diagnostic_stats" to "%s структурированных событий · %s КиБ · %s",
    "diagnostic_contents" to "Содержит жизненный цикл, маршруты экранов, безопасные действия, время API, состояние устройства и очищенные ошибки. Не содержит снимки экрана, звук, пароли/токены, тела запросов, игровой чат и SavedVariables.",
    "diagnostic_retention" to "При отправке диагностика хранится до 30 дней; обращение может остаться в истории поддержки.",
    "attach_diagnostics" to "Приложить этот диагностический снимок к отчёту",
    "quality_program" to "Программа улучшения качества",
    "quality_program_body" to "Необязательно. Разрешает использовать отчёт и очищенную диагностику для повышения надёжности, дизайна, доступности и интеграций.",
    "quality_program_opt_in" to "Использовать отчёт для улучшения SENTINEL",
    "physical_forensics" to "Диагностика физического теста",
    "physical_forensics_body" to "Эта изолированная тестовая сборка хранит расширенный локальный журнал. Экспортируйте его только при необходимости углублённой проверки.",
    "export_full_log" to "Экспорт полного журнала",
    "report_submit_failed" to "Не удалось отправить отчёт: %s",
    "report_received" to "Отчёт получен",
    "reference" to "Номер: %s",
    "status" to "Статус: %s",
    "problem_group" to "Группа проблемы: %s",
    "initial_severity" to "Начальная важность: %s",
    "related_reports" to "В этой группе уже %s связанных отчётов.",
    "diagnostics_attached" to "Диагностика приложена%s",
    "expires" to " · хранится до %s",
    "no_diagnostics_attached" to "Диагностика не приложена.",
    "sending" to "Отправка…",
    "submit_report" to "Отправить отчёт",
    "cancel" to "Отмена",
    "game_access" to "Доступ к играм",
    "no_entitlements" to "Этому аккаунту пока не назначен доступ к играм.",
    "valid_until" to "Действует до: %s",
    "sign_out" to "Выйти",
    "signing_out" to "Выход…",
    "game_details" to "Сведения об игре",
    "platform" to "Платформа: %s",
    "family" to "Семейство: %s",
    "versioning" to "Версии: %s",
    "launcher_supported" to "Поддержка лаунчера: %s",
    "interaction_mode" to "Режим взаимодействия: %s",
    "state_security" to "Состояние и защита",
    "algorithm" to "Алгоритм: %s",
    "bound" to "Подключено: %s",
    "last_seen" to "Последняя активность: %s",
    "fingerprint" to "Отпечаток: %s",
    "source" to "Источник: %s",
    "valid_from" to "Действует с: %s",
    "status_revoked" to "ОТКЛЮЧЕНО",
    "status_at_risk" to "ЕСТЬ РИСК",
    "rotate_key" to "Обновить ключ устройства",
    "revoke_device" to "Отключить устройство",
    "rotation_success" to "Ключ устройства успешно обновлён.",
    "revoked" to "Устройство отключено. Войдите снова, чтобы продолжить.",
    "settings_title" to "Настройки",
    "language" to "Язык",
    "language_system" to "Как в системе",
    "language_ru" to "Русский",
    "language_en" to "English",
    "appearance" to "Оформление",
    "theme_system" to "Как в системе",
    "theme_light" to "Светлая тема",
    "theme_dark" to "Тёмная тема",
    "settings_applied" to "Изменения применяются сразу и сохраняются на этом устройстве.",
    "updates_title" to "Обновление приложения",
    "current_version" to "Текущая версия",
    "build_channel" to "Канал",
    "channel_development" to "Разработка",
    "channel_diagnostic" to "Диагностическая APK",
    "channel_play" to "Google Play",
    "source_revision" to "Версия исходного кода",
    "check_updates" to "Проверить обновления",
    "install_update" to "Установить загруженное обновление",
    "checking_updates" to "Проверка обновлений…",
    "up_to_date" to "Установлена последняя доступная версия.",
    "update_available" to "Доступна новая версия.",
    "update_downloading" to "Google Play загружает обновление…",
    "update_ready" to "Обновление загружено и готово к установке.",
    "update_play_required" to "Безопасные автоматические обновления станут доступны после установки сборки из внутреннего тестирования Google Play.",
    "update_sideload_notice" to "Эта диагностическая APK-сборка установлена вне Google Play. При замене Android может запросить подтверждение или проверку Play Защиты.",
    "open_play_store" to "Открыть Google Play",
    "help_title" to "Справка",
    "help_getting_started" to "Начало работы",
    "help_getting_started_body" to "Войдите, подключите телефон, затем используйте центр управления для проверки защиты устройства и доступа к играм.",
    "help_security" to "Безопасность и конфиденциальность",
    "help_security_body" to "Пароли, токены сессии и закрытые ключи не попадают в экспортируемую диагностику. Ключи устройства остаются в Android Keystore.",
    "help_updates" to "Обновления",
    "help_updates_body" to "Откройте Меню → Обновление. Сборки из Google Play обновляются без удаления приложения и потери локального состояния.",
    "help_support" to "Поддержка",
    "help_support_body" to "Для воспроизводимой проблемы используйте пункт сообщения об ошибке или экспорт тестовых логов из красной панели.",
    "about_title" to "О SENTINEL",
    "about_body" to "SENTINEL — доверенная платформа игрока, объединяющая защиту устройства, доступ к играм, диагностику и интеллектуальные функции.",
    "diagnostic_build" to "Диагностическая сборка для физического теста",
    "games_title" to "Игры и доступ",
    "games_description" to "Назначенные аккаунту права доступа, подтверждённые сервером.",
    "activity_title" to "События",
    "activity_description" to "Серверная история действий аккаунта, защиты и подключений SENTINEL.",
    "activity_empty_title" to "Событий пока нет",
    "activity_empty_body" to "Новые события аккаунта и защиты появятся здесь после записи в SENTINEL Core.",
    "activity_event_allowed" to "Записано",
    "activity_event_denied" to "Отклонено",
    "activity_event_resource" to "Ресурс: %s",
    "activity_event_reason" to "Причина: %s",
    "activity_event_time" to "Время: %s",
    "activity_session" to "Сессия аккаунта активна",
    "activity_device" to "Идентификатор устройства подключён",
    "activity_logs" to "Диагностические события остаются на телефоне, пока вы явно не экспортируете или не приложите их.",
    "not_available" to "Недоступно",
    "yes" to "Да",
    "no" to "Нет",
    "back" to "Назад",
)
